In [1]:
!python -V

Python 3.9.12

In [2]:
import pandas as pd

In [7]:
df = pd.read_parquet('./data/green_tripdata_2025-01.parquet')

In [8]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-01-01 00:03:01,2025-01-01 00:17:12,N,1.0,75,235,1.0,5.93,24.70,...,0.5,6.80,0.00,NaN,1.0,34.00,1.0,1.0,0.00,0.0
1,2,2025-01-01 00:19:59,2025-01-01 00:25:52,N,1.0,166,75,1.0,1.32,8.60,...,0.5,0.00,0.00,NaN,1.0,11.10,2.0,1.0,0.00,0.0
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,N,5.0,171,73,1.0,0.41,25.55,...,0.0,0.00,0.00,NaN,1.0,26.55,2.0,2.0,0.00,0.0
3,2,2025-01-01 00:52:24,2025-01-01 01:07:52,N,1.0,74,223,1.0,4.12,21.20,...,0.5,6.13,6.94,NaN,1.0,36.77,1.0,1.0,0.00,0.0
4,2,2025-01-01 00:25:05,2025-01-01 01:01:10,N,1.0,66,158,1.0,4.71,33.80,...,0.5,7.81,0.00,NaN,1.0,46.86,1.0,1.0,2.75,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48321,2,2025-01-31 19:36:00,2025-01-31 20:05:00,None,NaN,179,132,NaN,13.99,55.61,...,0.5,11.42,0.00,NaN,1.0,68.53,NaN,NaN,NaN,NaN
48322,2,2025-01-31 20:33:00,2025-01-31 20:41:00,None,NaN,166,75,NaN,1.51,13.58,...,0.5,2.26,0.00,NaN,1.0,17.34,NaN,NaN,NaN,NaN
48323,2,2025-01-31 21:09:00,2025-01-31 21:30:00,None,NaN,41,42,NaN,2.90,30.89,...,0.5,0.00,0.00,NaN,1.0,32.39,NaN,NaN,NaN,NaN
48324,2,2025-01-31 22:22:00,2025-01-31 22:25:00,None,NaN,75,43,NaN,0.34,14.78,...,0.5,2.44,0.00,NaN,1.0,18.72,NaN,NaN,NaN,NaN
48325,2,2025-01-31 22:15:00,2025-01-31 22:22:00,None,NaN,42,194,NaN,1.37,66.67,...,0.5,10.00,6.94,NaN,1.0,85.11,NaN,NaN,NaN,NaN

In [10]:
df = df[df.trip_type == 2]

In [11]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,N,5.0,171,73,1.0,0.41,25.55,...,0.0,0.00,0.0,NaN,1.0,26.55,2.0,2.0,0.00,0.00
11,2,2025-01-01 00:18:31,2025-01-01 00:18:46,N,5.0,92,92,1.0,0.00,35.00,...,0.0,2.00,0.0,NaN,1.0,38.00,1.0,2.0,0.00,0.00
15,2,2025-01-01 00:31:59,2025-01-01 00:32:02,N,5.0,66,66,0.0,0.03,76.00,...,0.0,15.40,0.0,NaN,1.0,92.40,1.0,2.0,0.00,0.00
18,2,2025-01-01 00:20:31,2025-01-01 00:20:34,N,5.0,197,197,1.0,0.00,13.00,...,0.0,1.00,0.0,NaN,1.0,15.00,1.0,2.0,0.00,0.00
28,2,2025-01-01 00:48:38,2025-01-01 01:33:50,N,5.0,33,220,2.0,17.07,87.00,...,0.0,18.15,0.0,NaN,1.0,108.90,1.0,2.0,2.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46466,2,2025-01-31 23:59:44,2025-02-01 00:18:54,N,5.0,255,181,1.0,5.05,40.00,...,0.0,0.00,0.0,NaN,1.0,41.00,1.0,2.0,0.00,0.00
46467,2,2025-01-31 23:17:15,2025-01-31 23:17:40,N,5.0,40,40,1.0,0.00,12.00,...,0.0,2.60,0.0,NaN,1.0,15.60,1.0,2.0,0.00,0.00
46468,2,2025-02-01 23:17:15,2025-02-02 00:03:41,N,5.0,40,40,1.0,0.00,12.00,...,0.0,3.60,0.0,NaN,0.0,15.60,1.0,2.0,0.00,0.00
46469,2,2025-01-31 23:30:29,2025-01-31 23:33:47,N,5.0,255,112,1.0,0.78,15.00,...,0.0,2.00,0.0,NaN,1.0,18.00,1.0,2.0,0.00,0.00
46481,2,2025-01-31 23:51:11,2025-02-01 00:06:16,N,5.0,97,186,1.0,4.45,40.00,...,0.0,5.00,0.0,NaN,1.0,49.50,1.0,2.0,2.75,0.75

In [15]:
df.lpep_dropoff_datatime = pd.to_datetime(df.lpep_dropoff_datetime)
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)

/tmp/ipykernel_6689/3961002883.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.lpep_dropoff_datatime = pd.to_datetime(df.lpep_dropoff_datetime)
/tmp/ipykernel_6689/3961002883.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)

In [18]:
df['duration'] = df.lpep_dropoff_datetime - df.lpep_pickup_datetime

/tmp/ipykernel_6689/3059950210.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['duration'] = df.lpep_dropoff_datetime - df.lpep_pickup_datetime

In [19]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,duration
2,2,2025-01-01 00:05:29,2025-01-01 00:07:21,N,5.0,171,73,1.0,0.41,25.55,...,0.00,0.0,NaN,1.0,26.55,2.0,2.0,0.00,0.00,0 days 00:01:52
11,2,2025-01-01 00:18:31,2025-01-01 00:18:46,N,5.0,92,92,1.0,0.00,35.00,...,2.00,0.0,NaN,1.0,38.00,1.0,2.0,0.00,0.00,0 days 00:00:15
15,2,2025-01-01 00:31:59,2025-01-01 00:32:02,N,5.0,66,66,0.0,0.03,76.00,...,15.40,0.0,NaN,1.0,92.40,1.0,2.0,0.00,0.00,0 days 00:00:03
18,2,2025-01-01 00:20:31,2025-01-01 00:20:34,N,5.0,197,197,1.0,0.00,13.00,...,1.00,0.0,NaN,1.0,15.00,1.0,2.0,0.00,0.00,0 days 00:00:03
28,2,2025-01-01 00:48:38,2025-01-01 01:33:50,N,5.0,33,220,2.0,17.07,87.00,...,18.15,0.0,NaN,1.0,108.90,1.0,2.0,2.75,0.00,0 days 00:45:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46466,2,2025-01-31 23:59:44,2025-02-01 00:18:54,N,5.0,255,181,1.0,5.05,40.00,...,0.00,0.0,NaN,1.0,41.00,1.0,2.0,0.00,0.00,0 days 00:19:10
46467,2,2025-01-31 23:17:15,2025-01-31 23:17:40,N,5.0,40,40,1.0,0.00,12.00,...,2.60,0.0,NaN,1.0,15.60,1.0,2.0,0.00,0.00,0 days 00:00:25
46468,2,2025-02-01 23:17:15,2025-02-02 00:03:41,N,5.0,40,40,1.0,0.00,12.00,...,3.60,0.0,NaN,0.0,15.60,1.0,2.0,0.00,0.00,0 days 00:46:26
46469,2,2025-01-31 23:30:29,2025-01-31 23:33:47,N,5.0,255,112,1.0,0.78,15.00,...,2.00,0.0,NaN,1.0,18.00,1.0,2.0,0.00,0.00,0 days 00:03:18
46481,2,2025-01-31 23:51:11,2025-02-01 00:06:16,N,5.0,97,186,1.0,4.45,40.00,...,5.00,0.0,NaN,1.0,49.50,1.0,2.0,2.75,0.75,0 days 00:15:05